server.port=8082
spring.application.name=merchant-service
merchantService.api.base.path=/palaSarakku/merchant

# Common Kafka settings
spring.kafka.bootstrap-servers=localhost:9092
# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# product topic name
merchant.topic.name=merchant-events
#mongo
spring.data.mongodb.uri=mongodb+srv://dharunvdp2001:XjyeVdz2mNrgB5t7@catalogs.ew7s6.mongodb.net/?retryWrites=true&w=majority&appName=Catalogs
spring.data.mongodb.database=Catalogs