server.port=8084
spring.application.name=cart-order-service

# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.database=0

# Common Kafka settings
spring.kafka.bootstrap-servers=localhost:9092

# order topic name
order.topic.name=order-event
cartService.api.base.path=/palaSarakku/cart
cartOrderService.api.base.path=/palaSarakku/cart-order

#mongo
spring.data.mongodb.uri=mongodb+srv://dharunvdp2001:XjyeVdz2mNrgB5t7@catalogs.ew7s6.mongodb.net/?retryWrites=true&w=majority&appName=Catalogs
spring.data.mongodb.database=Catalogs

# Mailtrap Configuration ONLY
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=268687b3aa5bcc
spring.mail.password=56fe8b79d57017
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true