server.port=8083
spring.application.name=search-service
searchService.api.base.path=/palaSarakku/search

# Solr Configuration
spring.data.solr.host=http://localhost:8983/solr
spring.data.solr.collection=products_catalog_search

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
product.topic.name=product-events
merchant.topic.name=merchant-rating-event

# order topic name
order.topic.name=order-event